/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/products/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 상품 단건 조회
     * @description 존재하지 않는 id면 404.
     */
    get: operations["getProduct"];
    /**
     * 상품 수정
     * @description ADMIN 전용. name, sellingPrice, minStockLevel, categoryId만 수정 가능(sku/단가/재고는 불가).
     */
    put: operations["updateProduct"];
    post?: never;
    /**
     * 상품 삭제
     * @description ADMIN 전용. 연결된 재고 거래 이력이 있으면 409(DELETE_CONFLICT).
     */
    delete: operations["deleteProduct"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/categories/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * 카테고리 수정
     * @description ADMIN 전용. name, description만 수정 가능하며 부모 카테고리 이동은 지원하지 않습니다.
     */
    put: operations["updateCategory"];
    post?: never;
    /**
     * 카테고리 삭제
     * @description ADMIN 전용. 하위 카테고리나 소속 상품이 있으면 409(DELETE_CONFLICT).
     */
    delete: operations["deleteCategory"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stock/transactions/{id}/rollback": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 거래 롤백
     * @description ADMIN 전용. 상쇄 트랜잭션을 만들고 원본을 CANCELED 처리합니다. 조정 거래/이미 취소된 거래/롤백 거래는 불가, 재고가 음수가 되면 409(ROLLBACK_CONFLICT).
     */
    post: operations["rollbackStockTransaction"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stock/out": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 재고 출고
     * @description ADMIN/STAFF. unitPrice를 생략하면 상품의 sellingPrice를 사용합니다. 재고가 부족하면 409(INSUFFICIENT_STOCK).
     */
    post: operations["stockOut"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stock/in": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 재고 입고
     * @description ADMIN/STAFF. 가중평균으로 상품 매입단가(costPrice)를 갱신하고 재고를 증가시킵니다.
     */
    post: operations["stockIn"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stock/consume": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 재고 자체소비
     * @description ADMIN/STAFF. 폐기/내부사용/샘플(consumeType)로 재고를 차감하며 매출이 없는 전액 손실로 집계됩니다.
     */
    post: operations["stockConsume"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stock/adjustment": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 재고 조정
     * @description ADMIN 전용. 실사 수량(actualQuantity)으로 재고를 맞추고 차이를 ±로 기록합니다. reason 필수, 손익 계산에서는 제외됩니다.
     */
    post: operations["stockAdjustment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/products": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 상품 목록 검색
     * @description keyword(이름/SKU 부분일치), categoryId(하위 카테고리 포함), lowStockOnly 조건을 선택적으로 조합하고 페이징합니다.
     */
    get: operations["getProducts"];
    put?: never;
    /**
     * 상품 등록
     * @description ADMIN 전용. costPrice와 currentStock은 0으로 초기화됩니다(입고로만 증가).
     */
    post: operations["createProduct"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 카테고리 트리 조회
     * @description 전체 카테고리를 children이 중첩된 트리 구조로 반환합니다.
     */
    get: operations["getCategoryTree"];
    put?: never;
    /**
     * 카테고리 생성
     * @description ADMIN 전용. parentId가 없으면 최상위 카테고리, 존재하지 않는 parentId면 404.
     */
    post: operations["createCategory"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * 로그아웃
     * @description accessToken 쿠키를 만료시켜 브라우저가 삭제하도록 합니다.
     */
    post: operations["logout"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stock/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 거래내역 목록 조회
     * @description productId, type, status, 기간(startDate~endDate) 조건을 선택적으로 조합하고 페이징합니다. 롤백 트랜잭션도 포함됩니다.
     */
    get: operations["getTransactions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stock/transactions/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 거래내역 단건 조회
     * @description 롤백 전 확인용. 존재하지 않는 id면 404.
     */
    get: operations["getTransactionById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stock/profit-loss": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 손익 계산
     * @description 기간(startDate, endDate 필수) 내 ACTIVE 상태의 원본 출고/소비 거래만 집계합니다(롤백된 거래와 롤백 트랜잭션 제외). productId로 특정 상품만 볼 수 있습니다.
     */
    get: operations["getProfitLoss"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/stock/low-stock": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 재고 부족 상품 목록
     * @description currentStock이 minStockLevel 이하인 상품을 페이징하여 반환합니다.
     */
    get: operations["getLowStockProducts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * 내 정보 조회
     * @description 쿠키의 JWT로 인증된 현재 사용자의 id, email, role을 반환합니다. 로그인하지 않았으면 401.
     */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ProductUpdateRequest: {
      name: string;
      /** Format: int64 */
      categoryId: number;
      sellingPrice: number;
      /** Format: int32 */
      minStockLevel?: number;
    };
    ProductResponse: {
      /** Format: int64 */
      id: number;
      name: string;
      sku: string;
      /** Format: int64 */
      categoryId: number;
      /** @enum {string} */
      unit: "EA" | "G" | "ML";
      costPrice: number;
      sellingPrice: number;
      /** Format: int32 */
      currentStock: number;
      /** Format: int32 */
      minStockLevel: number;
    };
    CategoryUpdateRequest: {
      name: string;
      description?: string;
    };
    CategoryResponse: {
      /** Format: int64 */
      id: number;
      name: string;
      description: string;
      /** Format: int64 */
      parentId: number;
      /** Format: date-time */
      createdAt: string;
    };
    RollbackRequest: {
      reason: string;
    };
    StockTransactionResponse: {
      /** Format: int64 */
      id: number;
      /** Format: int64 */
      productId: number;
      /** Format: int64 */
      userId: number;
      /** @enum {string} */
      type: "IN" | "OUT" | "CONSUME" | "ADJUSTMENT";
      /** @enum {string} */
      status: "ACTIVE" | "CANCELED";
      /** Format: int32 */
      quantity: number;
      unitPrice: number;
      costPriceSnapshot: number;
      reason: string;
      /** Format: int64 */
      reversalOfId: number;
      /** Format: int64 */
      canceledBy: number;
      /** Format: date-time */
      canceledAt: string;
      /** Format: date-time */
      createdAt: string;
      /** @enum {string} */
      consumeType: "DISCARD" | "INTERNAL_USE" | "SAMPLE";
    };
    StockOutRequest: {
      /** Format: int64 */
      productId: number;
      /** Format: int32 */
      quantity: number;
      unitPrice?: number;
      reason?: string;
    };
    StockInRequest: {
      /** Format: int64 */
      productId: number;
      /** Format: int32 */
      quantity: number;
      unitPrice: number;
      reason?: string;
    };
    StockConsumeRequest: {
      /** Format: int64 */
      productId: number;
      /** Format: int32 */
      quantity: number;
      reason?: string;
      /** @enum {string} */
      consumeType: "DISCARD" | "INTERNAL_USE" | "SAMPLE";
    };
    StockAdjustmentRequest: {
      /** Format: int64 */
      productId: number;
      /** Format: int32 */
      actualQuantity: number;
      reason: string;
    };
    ProductCreateRequest: {
      name: string;
      sku: string;
      /** Format: int64 */
      categoryId: number;
      /** @enum {string} */
      unit: "EA" | "G" | "ML";
      sellingPrice: number;
      /** Format: int32 */
      minStockLevel?: number;
    };
    CategoryCreateRequest: {
      name: string;
      description?: string;
      /** Format: int64 */
      parentId?: number;
    };
    PageResponseStockTransactionResponse: {
      content: components["schemas"]["StockTransactionResponse"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      size: number;
      /** Format: int64 */
      totalElements: number;
      /** Format: int32 */
      totalPages: number;
    };
    ByProduct: {
      /** Format: int64 */
      productId: number;
      productName: string;
      profit: number;
      loss: number;
    };
    ProfitLossResponse: {
      totalRevenue: number;
      totalCost: number;
      totalProfit: number;
      consumeLoss: number;
      byProduct: components["schemas"]["ByProduct"][];
    };
    PageResponseProductResponse: {
      content: components["schemas"]["ProductResponse"][];
      /** Format: int32 */
      page: number;
      /** Format: int32 */
      size: number;
      /** Format: int64 */
      totalElements: number;
      /** Format: int32 */
      totalPages: number;
    };
    CategoryTreeResponse: {
      /** Format: int64 */
      id: number;
      name: string;
      description: string;
      children: components["schemas"]["CategoryTreeResponse"][];
    };
    UserInfo: {
      /** Format: int64 */
      id: number;
      email: string;
      role: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ProductResponse"];
        };
      };
    };
  };
  updateProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ProductResponse"];
        };
      };
    };
  };
  deleteProduct: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryUpdateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CategoryResponse"];
        };
      };
    };
  };
  deleteCategory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  rollbackStockTransaction: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RollbackRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StockTransactionResponse"];
        };
      };
    };
  };
  stockOut: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockOutRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StockTransactionResponse"];
        };
      };
    };
  };
  stockIn: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockInRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StockTransactionResponse"];
        };
      };
    };
  };
  stockConsume: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockConsumeRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StockTransactionResponse"];
        };
      };
    };
  };
  stockAdjustment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StockAdjustmentRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StockTransactionResponse"];
        };
      };
    };
  };
  getProducts: {
    parameters: {
      query?: {
        keyword?: string;
        categoryId?: number;
        lowStockOnly?: boolean;
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageResponseProductResponse"];
        };
      };
    };
  };
  createProduct: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProductCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ProductResponse"];
        };
      };
    };
  };
  getCategoryTree: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CategoryTreeResponse"][];
        };
      };
    };
  };
  createCategory: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CategoryCreateRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["CategoryResponse"];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getTransactions: {
    parameters: {
      query?: {
        productId?: number;
        type?: "IN" | "OUT" | "CONSUME" | "ADJUSTMENT";
        status?: "ACTIVE" | "CANCELED";
        startDate?: string;
        endDate?: string;
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageResponseStockTransactionResponse"];
        };
      };
    };
  };
  getTransactionById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["StockTransactionResponse"];
        };
      };
    };
  };
  getProfitLoss: {
    parameters: {
      query: {
        startDate: string;
        endDate: string;
        productId?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["ProfitLossResponse"];
        };
      };
    };
  };
  getLowStockProducts: {
    parameters: {
      query?: {
        /** @description Zero-based page index (0..N) */
        page?: number;
        /** @description The size of the page to be returned */
        size?: number;
        /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
        sort?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["PageResponseProductResponse"];
        };
      };
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "*/*": components["schemas"]["UserInfo"];
        };
      };
    };
  };
}
